name: Resume Creator from JSON
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Build Resume and Deploy on GitHub Pages 🚀
        uses: rajivnayanc/resume-creator-action@v4
        with:
          FileName: resume.json
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}